import { useMemo, useRef, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BarChart3, FileDown, RefreshCw, Search } from 'lucide-react'
import { formatCRC } from '@/shared/utils/currency'
import { isValidDateOnly, todayInCostaRica } from '@/shared/utils/date'
import { obtenerReporteFormaPago } from '../application/forma-pago-report.use-case'
import { generarReporteFormaPagoPdf } from '../application/forma-pago-report-pdf'
import type { FormaPagoReport, FormaPagoReportRow } from '../domain/forma-pago-report.types'
import { AxiosFormaPagoReportRepository } from '../infrastructure/axios-forma-pago-report.repository'
import './forma-pago-report.css'

const repository = new AxiosFormaPagoReportRepository()
const today = todayInCostaRica()
const initialFrom = `${today.slice(0, 8)}01`
const money = (value: number) => formatCRC(Number.isFinite(value) ? value : 0)

export function FormaPagoReportPage() {
  const [filters, setFilters] = useState({ fechaDesde: initialFrom, fechaHasta: today })
  const [report, setReport] = useState<FormaPagoReport | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [pdfError, setPdfError] = useState('')
  const [exporting, setExporting] = useState(false)
  const sequence = useRef(0)
  const chartRows = useMemo(() => { const rows = new Map<number | null, { formaPagoNombre: string; desembolsado: number; recibido: number }>(); for (const row of report?.desembolsos ?? []) rows.set(row.formaPagoId, { formaPagoNombre: row.formaPagoNombre, desembolsado: row.monto, recibido: 0 }); for (const row of report?.pagos ?? []) { const current = rows.get(row.formaPagoId) ?? { formaPagoNombre: row.formaPagoNombre, desembolsado: 0, recibido: 0 }; current.recibido = row.monto; rows.set(row.formaPagoId, current) } return [...rows.values()] }, [report])
  const update = (field: 'fechaDesde' | 'fechaHasta', value: string) => setFilters((current) => ({ ...current, [field]: value }))
  const consult = async () => { if (!isValidDateOnly(filters.fechaDesde) || !isValidDateOnly(filters.fechaHasta)) { setError('Ingresa fechas válidas.'); return } if (filters.fechaDesde > filters.fechaHasta) { setError('La fecha inicial no puede ser posterior a la fecha final.'); return } const request = ++sequence.current; setLoading(true); setError(''); setPdfError(''); try { const result = await obtenerReporteFormaPago(repository, filters.fechaDesde, filters.fechaHasta); if (request === sequence.current) setReport(result) } catch { if (request === sequence.current) { setReport(null); setError('No se pudo cargar el reporte por forma de pago.') } } finally { if (request === sequence.current) setLoading(false) } }
  const clear = () => { setFilters({ fechaDesde: initialFrom, fechaHasta: today }); setReport(null); setError(''); setPdfError('') }
  const exportPdf = () => { if (!report || exporting) return; setExporting(true); setPdfError(''); try { generarReporteFormaPagoPdf(report) } catch { setPdfError('No se pudo generar el PDF del reporte.') } finally { setExporting(false) } }
  return <main className="forma-pago-report-page"><div className="page-heading"><div><p className="eyebrow">FINANZAS / REPORTES</p><h1><BarChart3 size={25} aria-hidden="true" /> Reporte por forma de pago</h1><p className="muted">Desembolsos reales y pagos registrados agrupados por forma de pago.</p></div></div><div className="panel forma-pago-report-filters"><label>Fecha desde<input type="date" value={filters.fechaDesde} onChange={(event) => update('fechaDesde', event.target.value)} /></label><label>Fecha hasta<input type="date" value={filters.fechaHasta} onChange={(event) => update('fechaHasta', event.target.value)} /></label><div className="forma-pago-report-actions"><button className="primary-button" type="button" onClick={() => void consult()} disabled={loading || exporting}><Search size={16} /> {loading ? 'Consultando…' : 'Consultar'}</button><button className="secondary-button" type="button" onClick={clear} disabled={loading || exporting}>Limpiar</button><button className="secondary-button" type="button" onClick={exportPdf} disabled={loading || exporting || !report}>{exporting ? <RefreshCw size={16} /> : <FileDown size={16} />} {exporting ? 'Generando PDF…' : 'Exportar PDF'}</button></div></div>{error && <p className="form-error" role="alert">{error}</p>}{pdfError && <p className="form-error" role="alert">{pdfError}</p>}{loading && <div className="panel state-box" role="status">Cargando reporte...</div>}{!report && !loading && !error && <div className="panel state-box">Selecciona un período y consulta el reporte.</div>}{report && !loading && <FormaPagoReportContent report={report} chartRows={chartRows} />}</main>
}

function FormaPagoReportContent({ report, chartRows }: { report: FormaPagoReport; chartRows: Array<{ formaPagoNombre: string; desembolsado: number; recibido: number }> }) { const hasMovement = report.desembolsos.length > 0 || report.pagos.length > 0; return <><section className="forma-pago-report-cards">{[['Total desembolsado', report.resumen.totalDesembolsado], ['Total recibido', report.resumen.totalRecibido], ['Diferencia', report.resumen.diferencia]].map(([label, value]) => <div className="panel forma-pago-report-card" key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</section>{report.resumen.movimientosDesembolsoSinForma > 0 && <div className="panel forma-pago-report-warning" role="status">{report.resumen.movimientosDesembolsoSinForma} desembolso(s) no tienen forma de pago clasificable; no se inventó una categoría.</div>}{!hasMovement && <div className="panel state-box">No hay movimientos para el período seleccionado.</div>}<section className="panel forma-pago-chart"><h2>Desembolsado vs recibido por forma de pago</h2><div className="forma-pago-chart-canvas"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartRows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="formaPagoNombre" /><YAxis tickFormatter={(value) => money(Number(value))} /><Tooltip formatter={(value) => money(Number(value ?? 0))} /><Legend /><Bar dataKey="desembolsado" name="Desembolsado" fill="#276678" /><Bar dataKey="recibido" name="Recibido" fill="#2a9d8f" /></BarChart></ResponsiveContainer></div></section><section className="forma-pago-tables"><PaymentTable title="Desembolsos por forma de pago" rows={report.desembolsos} total={report.resumen.totalDesembolsado} /><PaymentTable title="Pagos recibidos por forma de pago" rows={report.pagos} total={report.resumen.totalRecibido} /></section></> }
 function PaymentTable({ title, rows, total }: { title: string; rows: FormaPagoReportRow[]; total: number }) { const totalQuantity = rows.reduce((sum, row) => sum + row.cantidad, 0); return <section className="panel forma-pago-table-panel"><h2>{title}</h2><div className="table-wrap"><table><thead><tr><th>Forma</th><th>Cantidad</th><th>Monto</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.formaPagoId ?? 'sin-forma'}-${row.formaPagoNombre}`}><th scope="row">{row.formaPagoNombre}</th><td>{row.cantidad}</td><td>{money(row.monto)}</td></tr>)}<tr className="forma-pago-total-row"><th scope="row">TOTAL</th><th scope="col">{totalQuantity}</th><th scope="col">{money(total)}</th></tr></tbody></table></div></section> }
