import { useEffect, useRef, useState } from 'react'
import { BarChart3, RefreshCw } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { formatCRC } from '@/shared/utils/currency'
import { formatDateOnly } from '@/shared/utils/date'
import { obtenerProyeccion } from '../application/proyeccion.use-cases'
import type { ProyeccionPeriodo, ProyeccionResponse } from '../domain/proyeccion.types'
import { AxiosProyeccionRepository } from '../infrastructure/axios-proyeccion.repository'
import './proyeccion-ganancias.css'

const repository = new AxiosProyeccionRepository(); const date = formatDateOnly
export function ProyeccionGananciasPage() {
  const [periodo, setPeriodo] = useState<ProyeccionPeriodo>('1m'); const [report, setReport] = useState<ProyeccionResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [retryCount, setRetryCount] = useState(0); const requestId = useRef(0)
  useEffect(() => { const id = ++requestId.current; setLoading(true); setError(''); void obtenerProyeccion(repository, periodo).then((value) => { if (id === requestId.current) setReport(value) }).catch(() => { if (id === requestId.current) { setReport(null); setError('No se pudo cargar la proyección contractual.') } }).finally(() => { if (id === requestId.current) setLoading(false) }) }, [periodo, retryCount])
  return <main className="proyeccion-page"><div className="page-heading"><div><p className="eyebrow">PRÉSTAMOS / REPORTES</p><h1><BarChart3 size={25} aria-hidden="true" /> Proyección contractual de ganancias</h1><p className="muted">Interés pendiente distribuido proporcionalmente sobre el plan operativo vigente dentro del horizonte seleccionado.</p></div></div><div className="panel proyeccion-toolbar"><label>Horizonte<select value={periodo} onChange={(event) => setPeriodo(event.target.value as ProyeccionPeriodo)}><option value="15d">15 días</option><option value="1m">1 mes</option><option value="2m">2 meses</option><option value="3m">3 meses</option><option value="cartera">Hasta finalizar cartera</option></select></label></div>{loading && <div className="panel state-box" role="status"><RefreshCw size={16} /> Cargando proyección...</div>}{!loading && error && <div className="panel state-box" role="alert">{error}<button className="secondary-button" onClick={() => setRetryCount((value) => value + 1)}>Reintentar</button></div>}{!loading && !error && report && <ProjectionView report={report} />}</main>
}
function ProjectionView({ report }: { report: ProyeccionResponse }) { const i = report.indicadores; return <><section className="proyeccion-metrics">{[['Ganancia cobrada', formatCRC(i.gananciaCobrado)], ['Ganancia pendiente', formatCRC(i.gananciaPendiente)], ['Proyectada período', formatCRC(i.gananciaProyectadaPeriodo)], ['Último pago programado', date(i.ultimoPagoProgramado)], ['Sin fecha', formatCRC(i.interesPendienteSinFecha)]].map(([label, value]) => <div className="panel proyeccion-metric" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="proyeccion-chart panel"><h2>Ganancia proyectada por mes</h2><ResponsiveContainer width="100%" height={220}><LineChart data={report.mensual}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="mes" /><YAxis tickFormatter={(value) => formatCRC(Number(value))} /><Tooltip formatter={(value) => formatCRC(Number(value ?? 0))} /><Line type="monotone" dataKey="ganancia" name="Ganancia" stroke="#e9a227" strokeWidth={2} /></LineChart></ResponsiveContainer></section><section className="panel table-wrap"><h2>Detalle mensual</h2><table><thead><tr><th>Mes</th><th>Ganancia</th></tr></thead><tbody>{report.mensual.map((row) => <tr key={row.mes}><th>{row.mes}</th><td>{formatCRC(row.ganancia)}</td></tr>)}</tbody></table></section><section className="panel table-wrap"><h2>Detalle por préstamo</h2><table><thead><tr><th>Préstamo / cliente</th><th>Interés total</th><th>Cobrado</th><th>Pendiente</th><th>Período</th><th>Cuotas futuras</th><th>Próximo pago</th><th>Último pago</th><th>Sin fecha</th></tr></thead><tbody>{report.prestamos.map((row) => <tr key={row.id}><th>#{row.id}<small>{row.cliente}</small></th><td>{formatCRC(row.interesTotal)}</td><td>{formatCRC(row.interesCobrado)}</td><td>{formatCRC(row.interesPendiente)}</td><td>{formatCRC(row.proyeccionPeriodo)}</td><td>{row.cuotasFuturas} · {formatCRC(row.totalCuotasFuturas)}</td><td>{date(row.proximoPago)}</td><td>{date(row.ultimoPagoProgramado)}</td><td>{formatCRC(row.interesPendienteSinFecha)}</td></tr>)}</tbody></table></section>{report.incobrable.prestamos.length > 0 && <p className="muted">INCOBRABLE separado: {formatCRC(report.incobrable.gananciaPendiente)} de interés pendiente en {report.incobrable.prestamos.length} préstamo(s).</p>}</> }
