import { ApiProperty } from '@nestjs/swagger';
import { ClienteResponseDto } from '../../../clientes/presentation/dto/cliente-response.dto';

class PrestamoCadenaDto { @ApiProperty() id!: number; @ApiProperty() clienteId!: number; @ApiProperty() estado!: string; @ApiProperty({ format: 'date' }) fechaAlta!: string; @ApiProperty() capital!: number; @ApiProperty() interes!: number; @ApiProperty() montoTotal!: number; @ApiProperty() montoDesembolsado!: number; }
class TransicionCadenaDto { @ApiProperty() refinanciamientoId!: number; @ApiProperty({ format: 'date' }) fecha!: string; @ApiProperty() prestamoOrigenId!: number; @ApiProperty() prestamoNuevoId!: number; @ApiProperty({ description: 'Capital pendiente trasladado desde el préstamo origen.' }) capitalTrasladado!: number; @ApiProperty({ description: 'Dinero nuevo efectivamente desembolsado por el préstamo nuevo.' }) dineroNuevoDesembolsado!: number; @ApiProperty({ description: 'Interés nuevo pactado en el refinanciamiento.' }) interesNuevo!: number; @ApiProperty({ nullable: true, format: 'date', description: 'Snapshot de la fecha máxima contractual del plan origen; null en históricos sin snapshot.' }) fechaLimiteContractualOrigen!: string | null; @ApiProperty({ nullable: true, description: 'Días calendario ganados, nunca negativo; null en históricos sin snapshot.' }) diasGanados!: number | null; }
class ResumenCadenaDto { @ApiProperty() cantidadPrestamos!: number; @ApiProperty() cantidadRefinanciamientos!: number; @ApiProperty() capitalInicial!: number; @ApiProperty() capitalTerminal!: number; @ApiProperty() totalCapitalTrasladado!: number; @ApiProperty() totalDineroNuevoDesembolsado!: number; @ApiProperty() totalInteresNuevoPactado!: number; @ApiProperty() diasGanadosAcumulados!: number; @ApiProperty({ description: 'False when any transition lacks a contractual-date snapshot.' }) diasGanadosCompletos!: boolean; @ApiProperty({ format: 'date' }) fechaUltimoRefinanciamiento!: string; }
class CadenaDto { @ApiProperty() prestamoRaizId!: number; @ApiProperty() prestamoTerminalId!: number; @ApiProperty({ format: 'date' }) fechaInicio!: string; @ApiProperty({ type: ResumenCadenaDto }) resumen!: ResumenCadenaDto; @ApiProperty({ type: [PrestamoCadenaDto] }) prestamos!: PrestamoCadenaDto[]; @ApiProperty({ type: [TransicionCadenaDto] }) transiciones!: TransicionCadenaDto[]; }
class ResumenGeneralDto { @ApiProperty() cantidadCadenas!: number; @ApiProperty() cantidadRefinanciamientos!: number; @ApiProperty() totalCapitalTrasladado!: number; @ApiProperty() totalDineroNuevoDesembolsado!: number; @ApiProperty() totalInteresNuevoPactado!: number; @ApiProperty() diasGanadosAcumulados!: number; @ApiProperty() diasGanadosCompletos!: boolean; }
export class CadenasClienteResponseDto { @ApiProperty({ type: ClienteResponseDto }) cliente!: ClienteResponseDto; @ApiProperty({ description: 'Criterio usado para fechaInicio y orden global.' }) convencionOrdenFechaInicio!: string; @ApiProperty({ type: ResumenGeneralDto }) resumen!: ResumenGeneralDto; @ApiProperty({ type: [CadenaDto] }) cadenas!: CadenaDto[]; }
