import { Refinanciamiento } from '../../../domain/entities/refinanciamiento';
import { ClienteRefinanciamientoResumen, RefinanciamientoConRelaciones, RefinanciamientoRelacion } from '../../../domain/repositories/refinanciamiento.repository';
import { RefinanciamientoOrmEntity } from './refinanciamiento.orm-entity';
const date = (v: string | Date) => v instanceof Date ? new Date(Date.UTC(v.getUTCFullYear(), v.getUTCMonth(), v.getUTCDate())) : new Date(`${v}T00:00:00.000Z`);
const nullableDate = (v: string | Date | null) => v == null ? null : date(v);
const relation = (p?: any): RefinanciamientoRelacion | undefined => p && ({ id: p.id, estado: p.estado, clienteId: p.clienteId, formaPagoId: p.formaPagoId, formaDesembolsoId: p.formaDesembolsoId ?? null, capital: p.capital, interes: p.interes, montoTotal: p.montoTotal, montoDesembolsado: p.montoDesembolsado });
const cliente = (c?: any): ClienteRefinanciamientoResumen | undefined => c && ({ id: c.id, identificacion: c.identificacion, nombreCompleto: [c.primerNombre, c.segundoNombre, c.primerApellido, c.segundoApellido].filter(Boolean).join(' ') });
export class RefinanciamientoMapper {
  static toDomain(e: RefinanciamientoOrmEntity): RefinanciamientoConRelaciones { return Object.assign(new Refinanciamiento(e.id, e.prestamoOrigenId, e.prestamoNuevoId, date(e.fecha), e.capitalPendiente, e.interesPendiente, e.montoRefinanciado, e.interesNuevo, e.observaciones, e.fechaCreacion, nullableDate(e.fechaLimiteContractualOrigen)), { cliente: cliente(e.prestamoOrigen?.cliente), prestamoOrigen: relation(e.prestamoOrigen), prestamoNuevo: relation(e.prestamoNuevo) }); }
  static toOrm(d: Refinanciamiento): RefinanciamientoOrmEntity { const e = new RefinanciamientoOrmEntity(); if (d.id !== null) e.id = d.id; e.prestamoOrigenId = d.prestamoOrigenId; e.prestamoNuevoId = d.prestamoNuevoId; e.fecha = d.fecha.toISOString().slice(0, 10); e.fechaLimiteContractualOrigen = d.fechaLimiteContractualOrigen?.toISOString().slice(0, 10) ?? null; e.capitalPendiente = d.capitalPendiente; e.interesPendiente = d.interesPendiente; e.montoRefinanciado = d.montoRefinanciado; e.interesNuevo = d.interesNuevo; e.observaciones = d.observaciones; return e; }
}
