import { useCallback, useEffect, useState } from 'react'
import { RefreshCw, Search } from 'lucide-react'
import Swal from 'sweetalert2'
import { Pagination } from '@/shared/components/Pagination'
import { formatCRC } from '@/shared/utils/currency'
import { AxiosPrestamoRepository } from '../infrastructure/axios-prestamo.repository'
import { anularPrestamo, listarAnulados, listarCandidatosAnulacion } from '../application/prestamos.use-cases'
import { prestamoErrorMessage } from '../domain/prestamo.error'
import type { AnuladoLoan, AnulacionesPage, Prestamo, PrestamoFilters, PrestamoPage } from '../domain/prestamo.types'
import './gestion-anulaciones.css'

const repository = new AxiosPrestamoRepository()
const localDate = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
const date = (value?: string | null) => value ? value.slice(0, 10).split('-').reverse().join('/') : '—'
const emptyLoans: PrestamoPage = { datos: [], pagina: 1, limite: 10, total: 0, totalPaginas: 0 }
const emptyCancelled: AnulacionesPage = { datos: [], pagina: 1, limite: 10, total: 0, totalPaginas: 0 }

export function GestionAnulacionesPage() {
  const [tab, setTab] = useState<'candidatos' | 'anulados'>('candidatos')
  const [candidates, setCandidates] = useState(emptyLoans); const [cancelled, setCancelled] = useState(emptyCancelled)
  const [filters, setFilters] = useState<PrestamoFilters>({ pagina: 1, limite: 10, ordenarPor: 'fechaAlta', direccionOrden: 'DESC' })
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState<Prestamo | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(''); try { if (tab === 'candidatos') setCandidates(await listarCandidatosAnulacion(repository, filters)); else setCancelled(await listarAnulados(repository, filters)) } catch (cause) { setError(prestamoErrorMessage(cause)) } finally { setLoading(false) } }, [filters, tab])
  useEffect(() => { void load() }, [load])
  const updateSearch = (value: string) => { setSearch(value); setFilters((current) => ({ ...current, buscar: value || undefined, pagina: 1 })) }
  const submit = async (fecha: string, observation: string) => { if (!selected || !fecha) return; try { await anularPrestamo(repository, selected.id, { fecha, ...(observation.trim() ? { observacion: observation.trim() } : {}) }); setSelected(null); const [nextCandidates, nextCancelled] = await Promise.all([listarCandidatosAnulacion(repository, { ...filters, pagina: 1 }), listarAnulados(repository, { ...filters, pagina: 1 })]); setCandidates(nextCandidates); setCancelled(nextCancelled); await Swal.fire({ toast: true, position: 'top-end', icon: 'success', title: 'Préstamo anulado correctamente.', showConfirmButton: false, timer: 2200 }) } catch (cause) { await Swal.fire({ icon: 'error', title: 'No se pudo anular el préstamo', text: prestamoErrorMessage(cause) }) } }
  const page = tab === 'candidatos' ? candidates : cancelled
  return <section className="gestion-anulaciones-page"><div className="page-heading"><div><p className="eyebrow">PRÉSTAMOS</p><h1>Gestión de anulaciones</h1><p className="muted">Registra anulaciones conservando el préstamo, el plan y su historial.</p></div><button className="secondary-button" onClick={() => void load()} disabled={loading}><RefreshCw size={16} /> Actualizar</button></div><div className="incobrables-tabs" role="tablist"><button className={tab === 'candidatos' ? 'active' : ''} onClick={() => { setTab('candidatos'); setFilters((current) => ({ ...current, pagina: 1 })) }}>Candidatos</button><button className={tab === 'anulados' ? 'active' : ''} onClick={() => { setTab('anulados'); setFilters((current) => ({ ...current, pagina: 1 })) }}>Anulados</button></div><div className="panel incobrables-toolbar"><label>Buscar cliente<input value={search} onChange={(event) => updateSearch(event.target.value)} placeholder="Identificación o nombre" /></label><Search size={18} aria-hidden="true" /></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="panel table-wrap">{loading ? <div className="state-box">Cargando información...</div> : !page.datos.length ? <div className="state-box">No hay registros para mostrar.</div> : tab === 'candidatos' ? <CandidatesTable loans={candidates.datos} onSelect={setSelected} /> : <CancelledTable loans={cancelled.datos} />}</div><Pagination pagina={page.pagina} totalPaginas={page.totalPaginas} total={page.total} limite={page.limite} opcionesLimite={[10, 25, 50, 100]} onPageChange={(pagina) => setFilters((current) => ({ ...current, pagina }))} onLimitChange={(limite) => setFilters((current) => ({ ...current, limite, pagina: 1 }))} label="préstamos" loading={loading} />{selected && <CancellationModal loan={selected} onClose={() => setSelected(null)} onSubmit={submit} />}</section>
}
function CandidatesTable({ loans, onSelect }: { loans: Prestamo[]; onSelect: (loan: Prestamo) => void }) { return <table><thead><tr><th>Préstamo</th><th>Cliente</th><th>Teléfono</th><th>Fecha</th><th>Capital</th><th>Desembolsado</th><th>Forma</th><th>Estado</th><th>Puede anular</th><th>Acción</th></tr></thead><tbody>{loans.map((loan) => <tr key={loan.id}><td>#{loan.id}</td><td><strong>{loan.cliente.nombreCompleto}</strong><small>{loan.cliente.identificacion}</small></td><td>{loan.cliente.telefono || '—'}</td><td>{date(loan.fechaAlta)}</td><td>{formatCRC(loan.capital)}</td><td>{formatCRC(loan.montoDesembolsado)}</td><td>{loan.formaDesembolso?.nombre || '—'}</td><td>{loan.estado}</td><td>{loan.puedeAnular ? 'Sí' : 'No'}</td><td><button className="primary-button" onClick={() => onSelect(loan)}>Anular préstamo</button></td></tr>)}</tbody></table> }
function CancelledTable({ loans }: { loans: AnuladoLoan[] }) { return <table><thead><tr><th>Préstamo / cliente</th><th>Teléfono</th><th>Fecha original</th><th>Capital</th><th>Desembolsado</th><th>Fecha anulación</th><th>Observación</th><th>Desembolso / reverso</th><th>Fecha reverso</th><th>Monto reversado</th><th>Usuario</th><th>Estado</th></tr></thead><tbody>{loans.map((loan) => <tr key={loan.id}><td><strong>#{loan.id} · {loan.cliente.nombreCompleto}</strong><small>{loan.cliente.identificacion}</small></td><td>{loan.cliente.telefono || '—'}</td><td>{date(loan.fechaAlta)}</td><td>{formatCRC(loan.capital)}</td><td>{formatCRC(loan.montoDesembolsado)}</td><td>{date(loan.fechaAnulacion)}</td><td>{loan.observacionAnulacion || '—'}</td><td>#{loan.movimientoDesembolsoId ?? '—'} → #{loan.movimientoReversoId ?? '—'}</td><td>{date(loan.fechaReverso)}</td><td>{loan.montoReversado == null ? '—' : formatCRC(loan.montoReversado)}</td><td>{loan.usuarioAnulacion?.nombreCompleto || '—'}</td><td>{loan.estado}</td></tr>)}</tbody></table> }
function CancellationModal({ loan, onClose, onSubmit }: { loan: Prestamo; onClose: () => void; onSubmit: (fecha: string, observation: string) => Promise<void> }) { const [fecha, setFecha] = useState(localDate()); const [observation, setObservation] = useState(''); return <div className="prestamo-cancellation-backdrop" role="presentation"><div className="prestamo-cancellation-modal" role="dialog" aria-modal="true" aria-labelledby="anulacion-title"><h2 id="anulacion-title">Anular préstamo #{loan.id}</h2><p><strong>{loan.cliente.nombreCompleto}</strong></p><p>Capital: {formatCRC(loan.capital)} · Desembolsado: {formatCRC(loan.montoDesembolsado)} · Fecha original: {date(loan.fechaAlta)} · Estado: ACTIVO</p><p className="modal-warning">Se creará en Caja un movimiento REVERSO por el monto desembolsado, vinculado al desembolso original. No se elimina el préstamo ni el plan; se conserva el historial y el estado cambia a ANULADO.</p><label className="prestamo-cancellation-field">Fecha económica *<input type="date" value={fecha} onChange={(event) => setFecha(event.target.value)} required /></label><label className="prestamo-cancellation-field">Observación<textarea value={observation} onChange={(event) => setObservation(event.target.value)} placeholder="Motivo de la anulación..." maxLength={500} /></label><div className="prestamo-detail-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={!fecha} onClick={() => void onSubmit(fecha, observation)}>Confirmar anulación</button></div></div></div> }
