const test = require('node:test');
const assert = require('node:assert/strict');
const { PrestamoEstadoHistorialService } = require('../dist/modules/prestamos/application/services/prestamo-estado-historial.service');
const { PrestamoEstadoHistorialMapper } = require('../dist/modules/prestamos/infrastructure/persistence/typeorm/prestamo-estado-historial.mapper');
const { EstadoPrestamo } = require('../dist/modules/prestamos/domain/enums/estado-prestamo.enum');

const date = value => new Date(`${value}T00:00:00.000Z`);
class Ledger {
  constructor() { this.rows = []; }
  async guardarEnTransaccion(_, row) { row.id = this.rows.length + 1; this.rows.push(row); return row; }
  async listarPorPrestamo(id) { return this.rows.filter(row => row.prestamoId === id).sort((a, b) => a.fecha - b.fecha || a.id - b.id); }
  async estadoDelPrestamoEnFecha(_, id, at) { const rows = this.rows.filter(row => row.prestamoId === id && row.fecha <= at).sort((a, b) => b.fecha - a.fecha || b.id - a.id); return rows[0]?.estadoNuevo ?? 'DESCONOCIDO'; }
}
const setup = () => { const ledger = new Ledger(); return { ledger, service: new PrestamoEstadoHistorialService(ledger) }; };
const register = (service, id, from, to, when = '2026-01-01', user = 7, note = null) => service.registrar({}, id, from, to, date(when), user, note);

test('initial transition is NULL to ACTIVO', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); assert.equal(ledger.rows[0].estadoAnterior, null); });
test('initial transition stores loan id', async () => { const { service, ledger } = setup(); await register(service, 9, null, EstadoPrestamo.ACTIVO); assert.equal(ledger.rows[0].prestamoId, 9); });
test('initial transition stores authenticated actor', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-01-01', 42); assert.equal(ledger.rows[0].usuarioId, 42); });
test('initial transition stores economic date', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-02-03'); assert.equal(ledger.rows[0].fecha.toISOString().slice(0, 10), '2026-02-03'); });
test('observation is trimmed', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-01-01', 7, ' note '); assert.equal(ledger.rows[0].observacion, 'note'); });
test('null observation remains null', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); assert.equal(ledger.rows[0].observacion, null); });
test('manual ACTIVO to INCOBRABLE is recorded', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE); assert.equal(ledger.rows.length, 1); });
test('manual INCOBRABLE to ACTIVO is recorded', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.INCOBRABLE, EstadoPrestamo.ACTIVO); assert.equal(ledger.rows[0].estadoNuevo, EstadoPrestamo.ACTIVO); });
test('ACTIVO to INCOBRABLE preserves previous state', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE); assert.equal(ledger.rows[0].estadoAnterior, EstadoPrestamo.ACTIVO); });
test('terminal CANCELADO can be represented by automatic event', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.CANCELADO); assert.equal(ledger.rows[0].estadoNuevo, EstadoPrestamo.CANCELADO); });
test('terminal REFINANCIADO can be represented by automatic event', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.REFINANCIADO); assert.equal(ledger.rows[0].estadoNuevo, EstadoPrestamo.REFINANCIADO); });
test('cycles are append-only', async () => { const { service, ledger } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE); await register(service, 1, EstadoPrestamo.INCOBRABLE, EstadoPrestamo.ACTIVO, '2026-01-02'); assert.equal(ledger.rows.length, 2); });
test('cycle resolves to latest ACTIVO', async () => { const { service } = setup(); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE); await register(service, 1, EstadoPrestamo.INCOBRABLE, EstadoPrestamo.ACTIVO, '2026-01-02'); assert.equal(await service.estadoDelPrestamoEnFecha({}, 1, date('2026-01-03')), EstadoPrestamo.ACTIVO); });
test('date lookup excludes future transition', async () => { const { service } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-02-01'); assert.equal(await service.estadoDelPrestamoEnFecha({}, 1, date('2026-01-31')), 'DESCONOCIDO'); });
test('date lookup includes transition on cutoff', async () => { const { service } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-02-01'); assert.equal(await service.estadoDelPrestamoEnFecha({}, 1, date('2026-02-01')), EstadoPrestamo.ACTIVO); });
test('missing history is explicit unknown', async () => { const { service } = setup(); assert.equal(await service.estadoDelPrestamoEnFecha({}, 77, date('2026-01-01')), 'DESCONOCIDO'); });
test('same date uses stable insertion order', async () => { const { service } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE); assert.equal(await service.estadoDelPrestamoEnFecha({}, 1, date('2026-01-01')), EstadoPrestamo.INCOBRABLE); });
test('different loans remain isolated', async () => { const { service } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); await register(service, 2, null, EstadoPrestamo.INCOBRABLE); assert.equal(await service.estadoDelPrestamoEnFecha({}, 1, date('2026-01-01')), EstadoPrestamo.ACTIVO); });
test('list is chronological', async () => { const { service } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO, '2026-02-01'); await register(service, 1, EstadoPrestamo.ACTIVO, EstadoPrestamo.INCOBRABLE, '2026-01-01'); assert.deepEqual((await service.listar(1)).map(row => row.estadoNuevo), [EstadoPrestamo.INCOBRABLE, EstadoPrestamo.ACTIVO]); });
test('list does not delete events', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); await service.listar(1); assert.equal(ledger.rows.length, 1); });
test('technical creation date is populated', async () => { const { service, ledger } = setup(); await register(service, 1, null, EstadoPrestamo.ACTIVO); assert.ok(ledger.rows[0].fechaCreacion instanceof Date); });
test('mapper exposes safe user identity only', () => { const entity = { id: 1, prestamoId: 2, estadoAnterior: null, estadoNuevo: EstadoPrestamo.ACTIVO, fecha: '2026-01-01', usuarioId: 3, observacion: null, fechaCreacion: new Date(), usuario: { id: 3, nombreCompleto: 'ADMIN', passwordHash: 'secret' } }; const result = PrestamoEstadoHistorialMapper.toDomain(entity); assert.deepEqual(result.usuario, { id: 3, nombreCompleto: 'ADMIN' }); assert.equal(result.usuario.passwordHash, undefined); });
test('mapper preserves nullable previous state', () => { const result = PrestamoEstadoHistorialMapper.toDomain({ id: 1, prestamoId: 2, estadoAnterior: null, estadoNuevo: EstadoPrestamo.ACTIVO, fecha: '2026-01-01', usuarioId: 3, observacion: null, fechaCreacion: new Date() }); assert.equal(result.estadoAnterior, null); });
test('mapper preserves new state', () => { const result = PrestamoEstadoHistorialMapper.toDomain({ id: 1, prestamoId: 2, estadoAnterior: EstadoPrestamo.ACTIVO, estadoNuevo: EstadoPrestamo.INCOBRABLE, fecha: '2026-01-01', usuarioId: 3, observacion: null, fechaCreacion: new Date() }); assert.equal(result.estadoNuevo, EstadoPrestamo.INCOBRABLE); });
test('mapper preserves observation', () => { const result = PrestamoEstadoHistorialMapper.toDomain({ id: 1, prestamoId: 2, estadoAnterior: null, estadoNuevo: EstadoPrestamo.ACTIVO, fecha: '2026-01-01', usuarioId: 3, observacion: 'audit', fechaCreacion: new Date() }); assert.equal(result.observacion, 'audit'); });
test('mapper preserves user id', () => { const result = PrestamoEstadoHistorialMapper.toDomain({ id: 1, prestamoId: 2, estadoAnterior: null, estadoNuevo: EstadoPrestamo.ACTIVO, fecha: '2026-01-01', usuarioId: 3, observacion: null, fechaCreacion: new Date() }); assert.equal(result.usuarioId, 3); });
test('history service delegates atomic manager to repository', async () => { const { service, ledger } = setup(); const manager = { marker: true }; await register(service, 1, null, EstadoPrestamo.ACTIVO); assert.equal(ledger.rows.length, 1); assert.ok(manager.marker); });
