export enum ModalidadPuestaEnMarcha {
  NEGOCIO_NUEVO = 'NEGOCIO_NUEVO',
  HISTORICO_COMPLETO = 'HISTORICO_COMPLETO',
  MIGRACION_SALDOS = 'MIGRACION_SALDOS',
}

export enum ProcedenciaSaldo {
  RECONSTRUIDO = 'RECONSTRUIDO',
  DECLARADO = 'DECLARADO',
  NO_APLICA = 'NO_APLICA',
}

export enum ConceptoSaldoPuesta {
  DISPONIBLE = 'DISPONIBLE',
  CARTERA_TOTAL = 'CARTERA_TOTAL',
  CARTERA_ACTIVA = 'CARTERA_ACTIVA',
  CARTERA_INCOBRABLE = 'CARTERA_INCOBRABLE',
}
