import { Body, ConflictException, Controller, Get, NotFoundException, Param, ParseIntPipe, Post, Query, Req } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource, In } from 'typeorm';
import { ApiBearerAuth, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { Roles } from '../../auth/auth.decorators';
import { RolUsuario } from '../../usuarios/domain/enums/rol-usuario.enum';
import { authenticatedUserId, AuthenticatedRequest } from '../../../common/authenticated-user';
import { ConfigurarFinanzasDto } from '../application/dto/configurar-finanzas.dto';
import { PeriodoDto } from '../application/dto/periodo.dto';
import { FinancialPeriodService } from '../application/financial-period.service';
import { CierreMensualOrmEntity, ConfiguracionFinancieraOrmEntity, DetalleCorteMensualOrmEntity } from '../domain/financial.orm-entities';
import { CierreMensualPreviewResponseDto, CierreMensualResponseDto } from './cierre-financiero-response.dto';

@Controller('configuracion-financiera')
@ApiBearerAuth()
@ApiTags('Cierre financiero')
export class ConfiguracionFinancieraController {
  constructor(@InjectDataSource() private readonly db: DataSource, private readonly service: FinancialPeriodService) {}
  @Get() @ApiOperation({ summary: 'Consultar configuración financiera' }) @ApiResponse({ status: 200, description: 'Configuración actual o null si aún no existe.' }) @ApiResponse({ status: 401, description: 'No autenticado.' }) async get() { const config = await this.db.getRepository(ConfiguracionFinancieraOrmEntity).findOne({ where: { singletonKey: 'FINANCIERA' } }); if (!config) return null; const { usuarioAperturaId, singletonKey, ...safe } = config; return safe; }
  @Get('vista-previa') @ApiOperation({ summary: 'Previsualizar cartera inicial' }) @ApiResponse({ status: 200, description: 'Cálculo informativo; no persiste datos.' }) @ApiResponse({ status: 400, description: 'Fecha inválida.' }) @ApiResponse({ status: 401, description: 'No autenticado.' }) preview(@Query('fecha') fecha: string) { this.service.assertDate(fecha); return this.db.transaction(m => this.service.openingSnapshot(m, fecha)); }
  @Post() @Roles(RolUsuario.ADMINISTRADOR) @ApiOperation({ summary: 'Abrir control financiero', description: 'La apertura es única y no admite una fecha futura respecto de la fecha económica de Costa Rica.' }) @ApiResponse({ status: 201, description: 'Configuración creada.' }) @ApiResponse({ status: 400, description: 'Datos inválidos o fecha futura.' }) @ApiResponse({ status: 401, description: 'No autenticado.' }) @ApiResponse({ status: 403, description: 'Rol insuficiente.' }) @ApiResponse({ status: 409, description: 'La configuración ya existe.' })
  create(@Body() dto: ConfigurarFinanzasDto, @Req() req: AuthenticatedRequest) { this.service.assertOpeningDate(dto.fechaApertura); return this.db.transaction(async manager => { if (await this.service.config(manager)) throw new ConflictException('La configuración financiera ya existe.'); const snapshot = await this.service.openingSnapshot(manager, dto.fechaApertura); return manager.getRepository(ConfiguracionFinancieraOrmEntity).save({ id: 1, singletonKey: 'FINANCIERA', fechaApertura: dto.fechaApertura, carteraInicial: snapshot.carteraTotal, carteraActivaInicial: snapshot.carteraActiva, carteraIncobrableInicial: snapshot.carteraIncobrable, disponibleInicial: dto.disponibleInicial, capitalSemillaHistorico: dto.capitalSemillaHistorico ?? null, observaciones: dto.observaciones?.trim() || null, usuarioAperturaId: authenticatedUserId(req) }); }); }
}

@Controller('cortes-mensuales')
@ApiBearerAuth()
@ApiTags('Cierre financiero')
export class CortesMensualesController {
  constructor(@InjectDataSource() private readonly db: DataSource, private readonly service: FinancialPeriodService) {}
  @Get('vista-previa') @ApiOperation({ summary: 'Previsualizar cierre mensual', description: 'Preview dinámica e informativa: no persiste, no crea Caja y excluye explícitamente el módulo Ingresos. La confirmación siempre recalcula.' }) @ApiResponse({ status: 200, type: CierreMensualPreviewResponseDto }) @ApiResponse({ status: 400, description: 'Período inválido.' }) @ApiResponse({ status: 401, description: 'No autenticado.' }) @ApiResponse({ status: 409, description: 'Salto o período ya cerrado.' }) preview(@Query() dto: PeriodoDto) { return this.db.transaction(m => this.service.previewClose(m, dto.anio, dto.mes)); }
  @Post('cerrar') @Roles(RolUsuario.ADMINISTRADOR) @ApiOperation({ summary: 'Confirmar cierre mensual', description: 'Solo ADMINISTRADOR. Recibe únicamente año, mes y observaciones; recalcula dentro de la transacción e inserta los 22 conceptos como snapshot inmutable. Ingresos externos están excluidos.' }) @ApiResponse({ status: 201, type: CierreMensualResponseDto }) @ApiResponse({ status: 400, description: 'Datos inválidos o invariantes financieras incumplidas.' }) @ApiResponse({ status: 401, description: 'No autenticado.' }) @ApiResponse({ status: 403, description: 'Rol insuficiente.' }) @ApiResponse({ status: 409, description: 'Período futuro, salto, duplicado o conflicto concurrente.' }) close(@Body() dto: PeriodoDto, @Req() req: AuthenticatedRequest) { return this.db.transaction(m => this.service.close(m, dto.anio, dto.mes, authenticatedUserId(req), dto.observaciones)); }
  @Get() @ApiOperation({ summary: 'Listar cierres mensuales', description: 'Lista snapshots históricos inmutables, sin recalcularlos.' }) @ApiResponse({ status: 200, type: CierreMensualResponseDto, isArray: true }) @ApiResponse({ status: 401, description: 'No autenticado.' }) async list() { const cierres = await this.db.getRepository(CierreMensualOrmEntity).find({ order: { fechaInicio: 'ASC' } }); if (!cierres.length) return cierres; const detalles = await this.db.getRepository(DetalleCorteMensualOrmEntity).find({ where: { corteId: In(cierres.map(c => c.id)) }, order: { id: 'ASC' } }); const byCorte = new Map<number, typeof detalles>(); for (const detalle of detalles) { const values = byCorte.get(detalle.corteId) ?? []; values.push(detalle); byCorte.set(detalle.corteId, values); } return cierres.map(cierre => ({ ...cierre, detalles: byCorte.get(cierre.id) ?? [] })); }
  @Get(':id') @ApiOperation({ summary: 'Consultar detalle de cierre mensual' }) @ApiResponse({ status: 200, type: CierreMensualResponseDto }) @ApiResponse({ status: 401, description: 'No autenticado.' }) @ApiResponse({ status: 404, description: 'Corte mensual no encontrado.' }) async get(@Param('id', ParseIntPipe) id: number) { const close = await this.db.getRepository(CierreMensualOrmEntity).findOne({ where: { id } }); if (!close) throw new NotFoundException('Corte mensual no encontrado.'); const detalles = await this.db.getRepository(DetalleCorteMensualOrmEntity).find({ where: { corteId: id }, order: { id: 'ASC' } }); return { ...close, detalles }; }
}
