import { EntityManager } from 'typeorm';
import { MovimientoCaja } from '../entities/movimiento-caja';
import { ConceptoMovimientoCaja } from '../enums/concepto-movimiento-caja.enum';
export interface FiltrosMovimientosCaja { pagina: number; limite: number; buscar?: string; tipo?: string; concepto?: ConceptoMovimientoCaja; conceptos?: ConceptoMovimientoCaja[]; usuarioId?: number; pagoId?: number; prestamoId?: number; refinanciamientoId?: number; fechaDesde?: string; fechaHasta?: string; }
export interface MovimientosPaginados { datos: MovimientoCaja[]; pagina: number; limite: number; total: number; totalPaginas: number; }
export interface TotalesCaja { totalEntradas: number; totalSalidas: number; balanceNeto: number; pagosClientes: number; desembolsosPrestamos: number; desembolsosRefinanciamientos: number; aportesCapital: number; retiros: number; gastos: number; ajustesEntrada: number; ajustesSalida: number; reversosEntrada: number; reversosSalida: number; porConcepto: Record<string, { entradas: number; salidas: number; balance: number }>; entradas?: number; salidas?: number; balance?: number; }
export interface RawEstadoMovimientoCaja { tipo: string; concepto: string; monto: string | number; cantidad?: string | number; }
export interface MovimientoCajaRepository { guardar(value: MovimientoCaja): Promise<MovimientoCaja>; guardarEnTransaccion(manager: EntityManager, value: MovimientoCaja): Promise<MovimientoCaja>; guardarManualIdempotente(manager: EntityManager, value: MovimientoCaja, fingerprint: string): Promise<{ movement: MovimientoCaja; replayed: boolean; fingerprint: string | null }>; buscarPorId(id: number): Promise<MovimientoCaja | null>; buscarPorIdEnTransaccion(manager: EntityManager, id: number, lock?: boolean): Promise<MovimientoCaja | null>; buscarPorPagoYConcepto(pagoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; buscarPorPagoYConceptoEnTransaccion(manager: EntityManager, pagoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; buscarPorRefinanciamientoYConcepto(refinanciamientoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; buscarPorRefinanciamientoYConceptoEnTransaccion(manager: EntityManager, refinanciamientoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; buscarPorPrestamoYConcepto(prestamoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; buscarPorPrestamoYConceptoEnTransaccion(manager: EntityManager, prestamoId: number, concepto: ConceptoMovimientoCaja): Promise<MovimientoCaja | null>; contarReversionesEnTransaccion(manager: EntityManager, movimientoId: number): Promise<number>; listar(filtros: FiltrosMovimientosCaja): Promise<MovimientosPaginados>; calcularTotales(filtros: Pick<FiltrosMovimientosCaja, 'buscar' | 'tipo' | 'concepto' | 'fechaDesde' | 'fechaHasta'>): Promise<TotalesCaja>; agregarEstado(fechaDesde: string, fechaHasta: string): Promise<{ rows: RawEstadoMovimientoCaja[]; count: number }>; }
export const MOVIMIENTO_CAJA_REPOSITORY = Symbol('MOVIMIENTO_CAJA_REPOSITORY');
