import { BadRequestException, Body, Controller, Get, Headers, NotFoundException, Param, ParseIntPipe, Post, Query, Req } from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags } from '@nestjs/swagger';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';
import { Inject } from '@nestjs/common';
import { CrearMovimientoCajaDto } from '../../application/dto/crear-movimiento-caja.dto';
import { FiltrosMovimientosCajaDto } from '../../application/dto/filtros-movimientos-caja.dto';
import { ReversarMovimientoCajaDto } from '../../application/dto/reversar-movimiento-caja.dto';
import { MovimientoCajaService } from '../../application/services/movimiento-caja.service';
import { EstadoMovimientosCajaService } from '../../application/services/estado-movimientos-caja.service';
import { EstadoMovimientosCajaDto, EstadoMovimientosCajaQueryDto } from '../../application/dto/estado-movimientos-caja.dto';
import { MOVIMIENTO_CAJA_REPOSITORY, MovimientoCajaRepository } from '../../domain/repositories/movimiento-caja.repository';
import { authenticatedUserId, AuthenticatedRequest } from '../../../../common/authenticated-user';
import { ConceptoMovimientoCaja } from '../../domain/enums/concepto-movimiento-caja.enum';
import { TipoMovimientoCaja } from '../../domain/enums/tipo-movimiento-caja.enum';
import { Roles } from '../../../auth/auth.decorators';
import { RolUsuario } from '../../../usuarios/domain/enums/rol-usuario.enum';

const date = (value: string) => new Date(`${value}T06:00:00.000Z`);

@ApiTags('Movimientos de caja')
@ApiBearerAuth()
@Controller('movimientos-caja')
@Roles(RolUsuario.ADMINISTRADOR)
export class MovimientosCajaController {
  constructor(@InjectDataSource() private readonly db: DataSource, private readonly service: MovimientoCajaService, private readonly estadoService: EstadoMovimientosCajaService, @Inject(MOVIMIENTO_CAJA_REPOSITORY) private readonly repo: MovimientoCajaRepository) {}
  @Post() @ApiOperation({ summary: 'Registrar movimiento manual', description: 'Solo APORTE_CAPITAL, RETIRO, GASTO, AJUSTE_ENTRADA y AJUSTE_SALIDA. El tipo se deriva del concepto. La fecha económica debe estar entre la apertura y hoy, en un período abierto. Las formas activas son obligatorias para aporte, retiro y gasto; opcionales para ajustes. Los ajustes requieren observaciones no vacías después de trim. El actor proviene del JWT. La clave Idempotency-Key es obligatoria: ASCII visible, 1–128 caracteres después de trim. La misma clave por actor con la misma huella devuelve el movimiento existente; con otra huella responde 409.' }) @ApiHeader({ name: 'Idempotency-Key', required: true, description: 'Opaque ASCII visible key, 1–128 characters after trimming spaces.' }) @ApiResponse({ status: 201, description: 'Movimiento creado o replay idempotente.' }) @ApiResponse({ status: 400, description: 'Datos inválidos, concepto automático, fecha futura/anterior a apertura/período cerrado, forma de pago inválida o configuración ausente.' }) @ApiResponse({ status: 404, description: 'Forma de pago inexistente.' }) @ApiResponse({ status: 409, description: 'La clave ya fue usada con otra solicitud.' })
  crear(@Body() dto: CrearMovimientoCajaDto, @Headers('idempotency-key') idempotencyKey: string | undefined, @Req() request: AuthenticatedRequest) { if (!idempotencyKey?.trim()) throw new BadRequestException('El header Idempotency-Key es obligatorio.'); return this.db.transaction(manager => this.service.crearManual(manager, { ...dto, idempotencyKey, fecha: date(dto.fecha), usuarioId: authenticatedUserId(request) })); }
  @Post(':id/reversar') @ApiOperation({ summary: 'Reversar movimiento manual sin mutar el original', description: 'Solo permite revertir movimientos manuales, nunca conceptos automáticos ni REVERSO. Crea un REVERSO con tipo opuesto, mismo monto y la misma forma de pago del original. La fecha debe estar entre apertura y hoy, en período abierto. Las observaciones son obligatorias después de trim. Una segunda reversión o reversión de un reverso responde 409/400.' }) @ApiParam({ name: 'id', type: Number }) @ApiResponse({ status: 400, description: 'Fecha futura, observaciones ausentes o movimiento automático/REVERSO.' }) @ApiResponse({ status: 404, description: 'Movimiento no encontrado o configuración ausente.' }) @ApiResponse({ status: 409, description: 'Movimiento ya reversado o período cerrado.' })
  reversar(@Param('id', ParseIntPipe) id: number, @Body() dto: ReversarMovimientoCajaDto, @Req() request: AuthenticatedRequest) { return this.db.transaction(manager => this.service.reversar(manager, id, date(dto.fecha), dto.observaciones.trim(), authenticatedUserId(request))); }
  @Get() @ApiOperation({ summary: 'Listar movimientos de caja', description: 'Ordenado por fecha económica descendente e identificador descendente. Los filtros se aplican sobre los movimientos registrados, incluyendo sus referencias y rango de fecha inclusivo. `conceptos` acepta una lista separada por comas y conserva compatibilidad con `concepto`.' }) @ApiResponse({ status: 200, description: 'Listado paginado de movimientos de caja.' }) @ApiQuery({ name: 'buscar', required: false, type: String }) @ApiQuery({ name: 'pagina', required: false, type: Number, minimum: 1 }) @ApiQuery({ name: 'limite', required: false, type: Number, minimum: 1, maximum: 100 }) @ApiQuery({ name: 'tipo', required: false, enum: ['ENTRADA', 'SALIDA'] }) @ApiQuery({ name: 'concepto', required: false, enum: ['PAGO_CLIENTE', 'DESEMBOLSO_PRESTAMO', 'DESEMBOLSO_REFINANCIAMIENTO', 'APORTE_CAPITAL', 'RETIRO', 'GASTO', 'AJUSTE_ENTRADA', 'AJUSTE_SALIDA', 'REVERSO'] }) @ApiQuery({ name: 'conceptos', required: false, type: String, description: 'Conceptos separados por coma.' }) @ApiQuery({ name: 'usuarioId', required: false, type: Number }) @ApiQuery({ name: 'pagoId', required: false, type: Number }) @ApiQuery({ name: 'prestamoId', required: false, type: Number }) @ApiQuery({ name: 'refinanciamientoId', required: false, type: Number }) @ApiQuery({ name: 'fechaDesde', required: false, type: String }) @ApiQuery({ name: 'fechaHasta', required: false, type: String }) listar(@Query() dto: FiltrosMovimientosCajaDto) { return this.repo.listar(dto); }
  @Get('resumen') @ApiOperation({ summary: 'Resumen bruto de dinero real de caja', description: 'Suma los montos registrados en caja, agrupados por concepto y dirección económica. Admite los mismos filtros de búsqueda, tipo, concepto y fecha que el listado. Las fechas son inclusivas.' }) @ApiResponse({ status: 200, description: 'Totales agregados de los movimientos que cumplen los filtros.' }) @ApiQuery({ name: 'buscar', required: false, type: String, description: 'Busca en observaciones, concepto y referencias.' }) @ApiQuery({ name: 'fechaDesde', required: false, type: String, description: 'Fecha económica inicial inclusiva (YYYY-MM-DD).' }) @ApiQuery({ name: 'fechaHasta', required: false, type: String, description: 'Fecha económica final inclusiva (YYYY-MM-DD).' }) @ApiQuery({ name: 'tipo', required: false, enum: TipoMovimientoCaja }) @ApiQuery({ name: 'concepto', required: false, enum: ConceptoMovimientoCaja }) resumen(@Query() dto: FiltrosMovimientosCajaDto) { return this.repo.calcularTotales(dto); }
  @Get('estado') @ApiOperation({ summary: 'Consultar estado histórico de caja', description: 'Reconstruye el disponible económico desde la apertura o el último cierre mensual aplicable, usando únicamente movimientos de Caja.' }) @ApiQuery({ name: 'fecha', required: false, type: String, format: 'date', example: '2026-09-16' }) @ApiResponse({ status: 200, type: EstadoMovimientosCajaDto }) @ApiResponse({ status: 400, description: 'Fecha inválida, futura o anterior a la apertura.' }) @ApiResponse({ status: 404, description: 'Configuración financiera no encontrada.' }) estado(@Query() dto: EstadoMovimientosCajaQueryDto) { return this.estadoService.obtener(dto.fecha); }
  @Get(':id') @ApiOperation({ summary: 'Consultar detalle de un movimiento de caja', description: 'Devuelve el movimiento inmutable, su actor, referencias y, cuando corresponde, el movimiento original que fue reversado y sus reversiones.' }) @ApiParam({ name: 'id', type: Number, description: 'Identificador del movimiento.' }) @ApiResponse({ status: 200, description: 'Detalle del movimiento y relaciones.', schema: { type: 'object', properties: { id: { type: 'number' }, tipo: { enum: Object.values(TipoMovimientoCaja) }, concepto: { enum: Object.values(ConceptoMovimientoCaja) }, monto: { type: 'number' }, fecha: { type: 'string', format: 'date' }, fechaCreacion: { type: 'string', format: 'date-time' }, usuarioId: { type: 'number' }, pagoId: { type: 'number', nullable: true }, prestamoId: { type: 'number', nullable: true }, refinanciamientoId: { type: 'number', nullable: true }, movimientoReversadoId: { type: 'number', nullable: true } } } }) @ApiResponse({ status: 404, description: 'Movimiento no encontrado.' }) async detalle(@Param('id', ParseIntPipe) id: number) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Movimiento de caja no encontrado.'); return value; }
}
