import { ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { FuenteIngreso } from '../../domain/entities/fuente-ingreso';
import { FUENTE_INGRESO_REPOSITORY, FuenteIngresoRepository } from '../../domain/repositories/fuente-ingreso.repository';
const duplicate = 'Ya existe una fuente de ingreso con ese nombre.';
@Injectable() export class CrearFuenteIngresoUseCase { constructor(@Inject(FUENTE_INGRESO_REPOSITORY) private repo: FuenteIngresoRepository) {} async execute(nombre: string) { const value = FuenteIngreso.crear(nombre); if (await this.repo.buscarPorNombre(value.nombre)) throw new ConflictException(duplicate); return this.repo.guardar(value); } }
@Injectable() export class ListarFuentesIngresoUseCase { constructor(@Inject(FUENTE_INGRESO_REPOSITORY) private repo: FuenteIngresoRepository) {} execute(activo?: boolean) { return this.repo.listar(activo); } }
@Injectable() export class ObtenerFuenteIngresoUseCase { constructor(@Inject(FUENTE_INGRESO_REPOSITORY) private repo: FuenteIngresoRepository) {} async execute(id: number) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Fuente de ingreso no encontrada.'); return value; } }
@Injectable() export class ActualizarFuenteIngresoUseCase { constructor(@Inject(FUENTE_INGRESO_REPOSITORY) private repo: FuenteIngresoRepository) {} async execute(id: number, nombre: string) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Fuente de ingreso no encontrada.'); const normalized = nombre.trim().toUpperCase(); const other = await this.repo.buscarPorNombre(normalized); if (other && other.id !== id) throw new ConflictException(duplicate); value.actualizarNombre(nombre); return this.repo.guardar(value); } }
@Injectable() export class CambiarEstadoFuenteIngresoUseCase { constructor(@Inject(FUENTE_INGRESO_REPOSITORY) private repo: FuenteIngresoRepository) {} async execute(id: number, activo: boolean) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Fuente de ingreso no encontrada.'); activo ? value.activar() : value.desactivar(); return this.repo.guardar(value); } }
