import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { FuenteIngresoRepository, FUENTE_INGRESO_REPOSITORY } from '../../domain/repositories/fuente-ingreso.repository';
import { Ingreso } from '../../domain/entities/ingreso';
import { FiltrosIngresos, INGRESO_REPOSITORY, IngresoRepository } from '../../domain/repositories/ingreso.repository';
const inactive = 'La fuente de ingreso seleccionada está inactiva.';
@Injectable() export class CrearIngresoUseCase { constructor(@Inject(INGRESO_REPOSITORY) private repo: IngresoRepository, @Inject(FUENTE_INGRESO_REPOSITORY) private sources: FuenteIngresoRepository) {} async execute(input: { fuenteIngresoId: number; fecha: string; monto: number; descripcion?: string }, usuarioId: number) { const source = await this.sources.buscarPorId(input.fuenteIngresoId); if (!source) throw new NotFoundException('Fuente de ingreso no encontrada.'); if (!source.activo) throw new BadRequestException(inactive); return this.repo.guardar(Ingreso.crear(input.fuenteIngresoId, input.fecha, input.monto, input.descripcion || null, usuarioId)); } }
@Injectable() export class ObtenerIngresoUseCase { constructor(@Inject(INGRESO_REPOSITORY) private repo: IngresoRepository) {} async execute(id: number) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Ingreso no encontrado.'); return value; } }
@Injectable() export class ListarIngresosUseCase { constructor(@Inject(INGRESO_REPOSITORY) private repo: IngresoRepository) {} execute(filters: FiltrosIngresos) { return this.repo.listar({ ...filters, limit: Math.min(filters.limit, 100) }); } }
@Injectable() export class ActualizarIngresoUseCase { constructor(@Inject(INGRESO_REPOSITORY) private repo: IngresoRepository, @Inject(FUENTE_INGRESO_REPOSITORY) private sources: FuenteIngresoRepository) {} async execute(id: number, input: { fuenteIngresoId: number; fecha: string; monto: number; descripcion?: string }) { const value = await this.repo.buscarPorId(id); if (!value) throw new NotFoundException('Ingreso no encontrado.'); const source = await this.sources.buscarPorId(input.fuenteIngresoId); if (!source) throw new NotFoundException('Fuente de ingreso no encontrada.'); if (!source.activo) throw new BadRequestException(inactive); value.fuenteIngresoId = input.fuenteIngresoId; value.fecha = input.fecha; value.monto = input.monto; value.descripcion = input.descripcion?.trim() || null; return this.repo.guardar(value); } }
