import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Brackets, EntityManager, Repository } from 'typeorm';
import { MovimientoCaja } from '../../../domain/entities/movimiento-caja';
import { ConceptoMovimientoCaja } from '../../../domain/enums/concepto-movimiento-caja.enum';
import { FiltrosMovimientosCaja, MovimientoCajaRepository, MovimientosPaginados, TotalesCaja } from '../../../domain/repositories/movimiento-caja.repository';
import { MovimientoCajaMapper } from './movimiento-caja.mapper';
import { MovimientoCajaOrmEntity } from './movimiento-caja.orm-entity';

@Injectable()
export class MovimientoCajaTypeOrmRepository implements MovimientoCajaRepository {
  constructor(@InjectRepository(MovimientoCajaOrmEntity) private readonly repo: Repository<MovimientoCajaOrmEntity>) {}
  private query(repo: Repository<MovimientoCajaOrmEntity>, filters: Partial<FiltrosMovimientosCaja>) {
    const query = repo.createQueryBuilder('m');
    if (filters.buscar?.trim()) { const term = `%${filters.buscar.trim()}%`; query.andWhere(new Brackets((where) => where.where('m.observaciones ILIKE :term', { term }).orWhere('m.concepto::text ILIKE :term', { term }).orWhere('CAST(m.pago_id AS TEXT) ILIKE :term', { term }).orWhere('CAST(m.prestamo_id AS TEXT) ILIKE :term', { term }).orWhere('CAST(m.refinanciamiento_id AS TEXT) ILIKE :term', { term }))); }
    if (filters.tipo) query.andWhere('m.tipo = :tipo', { tipo: filters.tipo }); if (filters.concepto) query.andWhere('m.concepto = :concepto', { concepto: filters.concepto }); if (filters.usuarioId) query.andWhere('m.usuario_id = :usuarioId', { usuarioId: filters.usuarioId }); if (filters.pagoId) query.andWhere('m.pago_id = :pagoId', { pagoId: filters.pagoId }); if (filters.prestamoId) query.andWhere('m.prestamo_id = :prestamoId', { prestamoId: filters.prestamoId }); if (filters.refinanciamientoId) query.andWhere('m.refinanciamiento_id = :refinanciamientoId', { refinanciamientoId: filters.refinanciamientoId }); if (filters.fechaDesde) query.andWhere('m.fecha >= :desde', { desde: filters.fechaDesde }); if (filters.fechaHasta) query.andWhere('m.fecha <= :hasta', { hasta: filters.fechaHasta }); return query;
  }
  async guardar(value: MovimientoCaja) { return MovimientoCajaMapper.toDomain(await this.repo.save(MovimientoCajaMapper.toOrm(value))); }
  async guardarEnTransaccion(manager: EntityManager, value: MovimientoCaja) { return MovimientoCajaMapper.toDomain(await manager.getRepository(MovimientoCajaOrmEntity).save(MovimientoCajaMapper.toOrm(value))); }
  async buscarPorId(id: number) { const entity = await this.repo.findOne({ where: { id }, relations: { pago: true, prestamo: true, refinanciamiento: true, usuario: true, movimientoReversado: true, reversiones: true } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorIdEnTransaccion(manager: EntityManager, id: number, lock = false) { const query = manager.getRepository(MovimientoCajaOrmEntity).createQueryBuilder('m').where('m.id = :id', { id }); if (lock) query.setLock('pessimistic_write'); const entity = await query.getOne(); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorPagoYConcepto(pagoId: number, concepto: ConceptoMovimientoCaja) { const entity = await this.repo.findOne({ where: { pagoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorRefinanciamientoYConcepto(refinanciamientoId: number, concepto: ConceptoMovimientoCaja) { const entity = await this.repo.findOne({ where: { refinanciamientoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorPagoYConceptoEnTransaccion(manager: EntityManager, pagoId: number, concepto: ConceptoMovimientoCaja) { const entity = await manager.getRepository(MovimientoCajaOrmEntity).findOne({ where: { pagoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorRefinanciamientoYConceptoEnTransaccion(manager: EntityManager, refinanciamientoId: number, concepto: ConceptoMovimientoCaja) { const entity = await manager.getRepository(MovimientoCajaOrmEntity).findOne({ where: { refinanciamientoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorPrestamoYConcepto(prestamoId: number, concepto: ConceptoMovimientoCaja) { const entity = await this.repo.findOne({ where: { prestamoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async buscarPorPrestamoYConceptoEnTransaccion(manager: EntityManager, prestamoId: number, concepto: ConceptoMovimientoCaja) { const entity = await manager.getRepository(MovimientoCajaOrmEntity).findOne({ where: { prestamoId, concepto } }); return entity ? MovimientoCajaMapper.toDomain(entity) : null; }
  async contarReversionesEnTransaccion(manager: EntityManager, movimientoId: number) { return manager.getRepository(MovimientoCajaOrmEntity).count({ where: { movimientoReversadoId: movimientoId } }); }
  async listar(filters: FiltrosMovimientosCaja): Promise<MovimientosPaginados> { const [entities, total] = await this.query(this.repo, filters).orderBy('m.fecha', 'DESC').addOrderBy('m.id', 'DESC').skip((filters.pagina - 1) * filters.limite).take(filters.limite).getManyAndCount(); return { datos: entities.map(MovimientoCajaMapper.toDomain), pagina: filters.pagina, limite: filters.limite, total, totalPaginas: Math.ceil(total / filters.limite) }; }
  async calcularTotales(filters: Pick<FiltrosMovimientosCaja, 'fechaDesde' | 'fechaHasta'>): Promise<TotalesCaja> { const rows = await this.query(this.repo, filters).select('m.tipo', 'tipo').addSelect('m.concepto', 'concepto').addSelect('SUM(CASE WHEN m.tipo = :entrada THEN m.monto ELSE 0 END)', 'entradas').addSelect('SUM(CASE WHEN m.tipo = :salida THEN m.monto ELSE 0 END)', 'salidas').groupBy('m.tipo').addGroupBy('m.concepto').setParameters({ entrada: 'ENTRADA', salida: 'SALIDA' }).getRawMany<{ tipo: string; concepto: string; entradas: string; salidas: string }>(); const result: TotalesCaja = { totalEntradas: 0, totalSalidas: 0, balanceNeto: 0, pagosClientes: 0, desembolsosPrestamos: 0, desembolsosRefinanciamientos: 0, aportesCapital: 0, retiros: 0, gastos: 0, ajustesEntrada: 0, ajustesSalida: 0, reversosEntrada: 0, reversosSalida: 0, porConcepto: {} }; const names: Record<string, keyof TotalesCaja> = { PAGO_CLIENTE: 'pagosClientes', DESEMBOLSO_PRESTAMO: 'desembolsosPrestamos', DESEMBOLSO_REFINANCIAMIENTO: 'desembolsosRefinanciamientos', APORTE_CAPITAL: 'aportesCapital', RETIRO: 'retiros', GASTO: 'gastos', AJUSTE_ENTRADA: 'ajustesEntrada', AJUSTE_SALIDA: 'ajustesSalida' }; for (const row of rows) { const entradas = Number(row.entradas); const salidas = Number(row.salidas); const amount = entradas + salidas; result.totalEntradas += entradas; result.totalSalidas += salidas; result.porConcepto[row.concepto] ??= { entradas: 0, salidas: 0, balance: 0 }; result.porConcepto[row.concepto].entradas += entradas; result.porConcepto[row.concepto].salidas += salidas; const field = names[row.concepto]; if (field) (result[field] as number) += amount; else if (row.concepto === 'REVERSO') result[row.tipo === 'ENTRADA' ? 'reversosEntrada' : 'reversosSalida'] += amount; } result.balanceNeto = result.totalEntradas - result.totalSalidas; for (const values of Object.values(result.porConcepto)) values.balance = values.entradas - values.salidas; result.entradas = result.totalEntradas; result.salidas = result.totalSalidas; result.balance = result.balanceNeto; return result; }
}
