import { Injectable } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';
import { ANALISIS_FINANCIERO_REPOSITORY, AnalisisFinancieroRepository } from '../../../domain/repositories/analisis-financiero.repository';

@Injectable()
export class AnalisisFinancieroTypeOrmRepository implements AnalisisFinancieroRepository {
  constructor(@InjectDataSource() private readonly db: DataSource) {}
  async listarPrestamos(clienteId: number) { const rows = await this.db.createQueryBuilder().select(['prestamo.id AS id', 'prestamo.estado AS estado', 'prestamo.fecha_alta AS "fechaAlta"', 'prestamo.capital AS capital', 'prestamo.interes AS interes', 'prestamo.monto_total AS "montoTotal"', 'prestamo.cantidad_pagos AS "cantidadPagos"', 'periodicidad.nombre AS periodicidad']).from('prestamo', 'prestamo').innerJoin('periodicidad_pago', 'periodicidad', 'periodicidad.id = prestamo.periodicidad_pago_id').where('prestamo.cliente_id = :clienteId', { clienteId }).orderBy('prestamo.fecha_alta', 'DESC').addOrderBy('prestamo.id', 'DESC').getRawMany(); return rows.map((r) => ({ ...r, id: Number(r.id), capital: Number(r.capital), interes: Number(r.interes), montoTotal: Number(r.montoTotal), cantidadPagos: Number(r.cantidadPagos), fechaAlta: new Date(`${r.fechaAlta}T00:00:00Z`) })); }
  async obtenerTotalesPagos(ids: number[]) { return this.db.createQueryBuilder().select('pago.prestamo_id', 'prestamoId').addSelect('SUM(pago.monto)', 'monto').addSelect('SUM(pago.capital_aplicado)', 'capital').addSelect('SUM(pago.interes_aplicado)', 'interes').from('pago', 'pago').where('pago.prestamo_id IN (:...ids)', { ids }).groupBy('pago.prestamo_id').getRawMany().then(rows => rows.map(r => ({ prestamoId: Number(r.prestamoId), monto: Number(r.monto), capital: Number(r.capital), interes: Number(r.interes) }))); }
  async listarUltimosPagos(ids: number[]) { return this.db.createQueryBuilder().select('pago.id', 'id').addSelect('pago.prestamo_id', 'prestamoId').addSelect('pago.monto', 'monto').addSelect('pago.capital_aplicado', 'capitalAplicado').addSelect('pago.interes_aplicado', 'interesAplicado').addSelect('pago.fecha', 'fecha').from('pago', 'pago').where('pago.prestamo_id IN (:...ids)', { ids }).andWhere('pago.id IN (SELECT DISTINCT ON (p2.prestamo_id) p2.id FROM pago p2 WHERE p2.prestamo_id IN (:...ids) ORDER BY p2.prestamo_id, p2.fecha DESC, p2.id DESC)', { ids }).getRawMany().then(rows => rows.map(r => ({ ...r, id: Number(r.id), prestamoId: Number(r.prestamoId), monto: Number(r.monto), capitalAplicado: Number(r.capitalAplicado), interesAplicado: Number(r.interesAplicado) }))); }
  async listarPagosOrdenados(ids: number[]) { return this.db.createQueryBuilder().select('pago.id', 'id').addSelect('pago.prestamo_id', 'prestamoId').addSelect('pago.monto', 'monto').addSelect('pago.capital_aplicado', 'capitalAplicado').addSelect('pago.interes_aplicado', 'interesAplicado').addSelect('pago.fecha', 'fecha').from('pago', 'pago').where('pago.prestamo_id IN (:...ids)', { ids }).orderBy('pago.prestamo_id', 'ASC').addOrderBy('pago.fecha', 'ASC').addOrderBy('pago.id', 'ASC').getRawMany().then(rows => rows.map(r => ({ ...r, id: Number(r.id), prestamoId: Number(r.prestamoId), monto: Number(r.monto), capitalAplicado: Number(r.capitalAplicado), interesAplicado: Number(r.interesAplicado) }))); }
  async listarRefinanciamientos(ids: number[]) { return this.db.createQueryBuilder().select('ref.prestamo_origen_id', 'prestamoOrigenId').addSelect('ref.fecha', 'fecha').from('refinanciamiento', 'ref').where('ref.prestamo_origen_id IN (:...ids)', { ids }).getRawMany().then(rows => rows.map(r => ({ prestamoOrigenId: Number(r.prestamoOrigenId), fecha: r.fecha }))); }
  async listarObligacionesVencidas(ids: number[], hoy: string) { const rows = await this.db.createQueryBuilder().select('plan.prestamo_id', 'prestamoId').from('plan_pago', 'plan').leftJoin('pago', 'pago', 'pago.plan_pago_id = plan.id').where('plan.prestamo_id IN (:...ids)', { ids }).andWhere('plan.fecha_vencimiento < :hoy', { hoy }).groupBy('plan.id').addGroupBy('plan.prestamo_id').addGroupBy('plan.monto_programado').having('COALESCE(SUM(pago.monto), 0) < plan.monto_programado').getRawMany(); return rows.map(r => Number(r.prestamoId)); }
}
